---
apiVersion: v1
kind: Secret
metadata:
  name: azure-creator
  namespace: upbound-system
type: Opaque
stringData:
  "credentials": |-
    {
      "clientSecret": "...,
      "clientId": "...,
      "tenantId": "...,
      "subscriptionId": "..."
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: gcp-creator
  namespace: upbound-system
type: Opaque
stringData:
  "credentials": |-
    {
      "type": "...",
      "project_id": "...",
      "private_key_id": "...",
      "private_key": "-----BEGIN PRIVATE KEY-----\n...\n-----END PRIVATE KEY-----\n",
      "client_email": "...",
      "client_id": "...",
      "auth_uri": "...",
      "token_uri": "...",
      "auth_provider_x509_cert_url": "...",
      "client_x509_cert_url": "...",
      "universe_domain": "...m"
    }
---
apiVersion: tf.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: terraform-azure
spec:
  credentials:
    - filename: terraform.tfvars.json  # if this filename will be used vars will be mounted to terraform by default
      source: Secret
      secretRef:
        namespace: upbound-system
        name: azure-creator
        key: credentials
  configuration: |-
    terraform {
      backend "kubernetes" {
        secret_suffix     = "providerconfig-azure"
        namespace         = "upbound-system"
        in_cluster_config = true
      }
      required_providers {
        azresourcegraph = {
          source  = "tiwood/azresourcegraph"
          version = "0.2.0"
        }
        azapi = {
          source = "azure/azapi"
        }
      }
    }
---
apiVersion: tf.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: terraform-gcp
spec:
  credentials:
    - filename: gcp-credentials.json
      source: Secret
      secretRef:
        namespace: upbound-system
        name: gcp-creator
        key: credentials
  configuration: |-              
    terraform {
      backend "kubernetes" {
        secret_suffix     = "providerconfig-azure"
        namespace         = "upbound-system"
        in_cluster_config = true
      }
    }