---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xnetworkwatchers.demo.io
spec:
  group: demo.io
  defaultCompositeDeletePolicy: Foreground
  defaultCompositionRef:
    name: xnetworkwatchers.demo.io
  names:
    kind: XNetworkWatcher
    plural: xnetworkwatchers
    singular: xnetworkwatcher
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - location
                - subscriptionId
              properties:
                location:
                  description: 'location: Cloud region for Network Watcher'
                  type: string
                subscriptionId:
                  description: 'subscriptionId: subscription Id in which Network Watcher was created'
                  type: string
