---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xnetworks.demo.io
spec:
  group: demo.io
  defaultCompositeDeletePolicy: Foreground
  defaultCompositionRef:
    name: xvnets.demo.io
  names:
    kind: XNetwork
    plural: xnetworks
    singular: xnetwork
  claimNames:
    kind: Network
    plural: networks
    singular: network
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - networkName
                - cloudRegion
                - subnets
                - accountID
              properties:
                accountID:
                  description: 'accountID: Id of the subscription/project'
                  type: string
                networkName:
                  description: 'networkName: will be used to create names of your resources'
                  type: string
                peerNetworkName:
                  description: 'peerNetworkName: name of network to which your network will be peered'
                  type: string
                cloudRegion:
                  description: 'CloudRegion: one of Azure regions possible values
                    values: "germanywestcentral" "westeurope"'
                  type: string
                  enum:
                    - germanywestcentral
                    - westeurope
                    - us-west2
                subnets:
                  description: 'Subnets cidrs'
                  type: array
                  items:
                    type: string
            status:
              type: object
              properties:
                peerVnetId:
                  description: 'peerVnetId: Id of the Peered Vnet'
                  type: string
                vnetId:
                  description: 'vnetId: Id of the created Vnet'
                  type: string
                rgpName:
                  description: 'rgpName: Created rgp name'
                  type: string
